### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [moritz/svg#6]
1.
Can you please set a specific "version" for your RAKU module in your META6.json file?
You have a '*" now, which is known to make trouble and may not be supported within the RAKU tool chain (soon), say ZEF, FEZ, MI6...

2.
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?
I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by AntonOks** [comment]
@moritz @zoffixznet ping...

**Comment by moritz** [comment]
I've bumped the version to 1.0 and tagged it.

**Comment by AntonOks** [comment]
> I've bumped the version to 1.0 and tagged it.

THANKS!

P.S.: May I ask for another favor :O in the future, it would be nice if you could keep the META6.json versions and the "git tag" versions in sync. Right now, META6 says "1.0" and the "git tag" has "**v**1.0"

**Comment by moritz** [comment]
isn't that usual, to prefix versions in tags with a `v`?

And where can I find documentation how it's all supposed to work?

**Comment by AntonOks** [comment]
> isn't that usual, to prefix versions in tags with a `v`?

I would say, as long as it's consistent 

> And where can I find documentation how it's all supposed to work?

What exactly do you mean with "supposed to work"? Or better "what" do you mean?
For Star, I've started / opened / added / enabled
- [Wiki](https://github.com/rakudo/star/wiki)
- [Discussions](https://github.com/rakudo/star/discussions)

and hope people will ask / document / discuss Star related things there...

**Comment by moritz** [comment]
> I would say, as long as it's consistent

The difference is that tags can be used for things other than versions, so having a `v` for a version prefix makes sense to me. It doesn't make sense to me to use the `v` prefix in a `version` field.

> What exactly do you mean with "supposed to work"? Or better "what" do you mean?

How modules and their meta data (including git repos) are supposed to be structured to be friendly for inclusion in rakudo star.
